// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIF7CulGwlGrQXZAFJnyutsIXDzBKp2ME',
    appId: '1:420669118527:web:ee536fe1495e5fefd8c08a',
    messagingSenderId: '420669118527',
    projectId: 'fir-test-e820f',
    authDomain: 'fir-test-e820f.firebaseapp.com',
    storageBucket: 'fir-test-e820f.appspot.com',
    measurementId: 'G-FPD7RTHSJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3i3CP1d4XyPWfwUoy6i5eRW3Y68IXUv0',
    appId: '1:420669118527:android:5dce51e46d3127eed8c08a',
    messagingSenderId: '420669118527',
    projectId: 'fir-test-e820f',
    storageBucket: 'fir-test-e820f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-1itE-mdI-LMTg_mFXuhvJ63RtECM5XQ',
    appId: '1:420669118527:ios:4e31449bb493e8bdd8c08a',
    messagingSenderId: '420669118527',
    projectId: 'fir-test-e820f',
    storageBucket: 'fir-test-e820f.appspot.com',
    iosClientId: '420669118527-f4k6m3ukuotv3npnj322cf77n3etuhat.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-1itE-mdI-LMTg_mFXuhvJ63RtECM5XQ',
    appId: '1:420669118527:ios:4e31449bb493e8bdd8c08a',
    messagingSenderId: '420669118527',
    projectId: 'fir-test-e820f',
    storageBucket: 'fir-test-e820f.appspot.com',
    iosClientId: '420669118527-f4k6m3ukuotv3npnj322cf77n3etuhat.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
